import { StyleSheet } from 'react-native';

export const PromotionEditorStyles = StyleSheet.create({
  card: {
    borderWidth: 1,
    borderColor: '#BAE6FD',
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    padding: 14,
    marginBottom: 14,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  headerTitleRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 10,
  },
  headerIcon: {
    width: 42,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: '#E0F2FE',
  },
  headerEyebrow: {
    color: '#0284C7',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  title: {
    color: '#0F172A',
    fontSize: 17,
    fontWeight: '900',
    marginTop: 2,
  },
  closeButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: '#F1F5F9',
  },
  field: {
    marginBottom: 14,
  },
  label: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  input: {
    minHeight: 62,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 18,
    backgroundColor: '#F8FAFC',
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 21,
    paddingHorizontal: 14,
    paddingVertical: 12,
    textAlignVertical: 'top',
  },
  dateRow: {
    flexDirection: 'row',
    columnGap: 10,
    marginBottom: 14,
  },
  dateField: {
    flex: 1,
  },
  dateInputBox: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 18,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 12,
    columnGap: 8,
  },
  dateText: {
    flex: 1,
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '800',
  },
  daysRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  dayCircle: {
    width: 39,
    height: 39,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
  },
  dayCircleActive: {
    borderColor: '#0284C7',
    backgroundColor: '#0284C7',
  },
  dayText: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '900',
  },
  dayTextActive: {
    color: '#FFFFFF',
  },
  timeToggleContainer: {
    flexDirection: 'row',
    borderRadius: 18,
    backgroundColor: '#F1F5F9',
    padding: 4,
    marginBottom: 14,
  },
  timeToggleButton: {
    flex: 1,
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
  },
  timeToggleButtonActive: {
    backgroundColor: '#FFFFFF',
  },
  timeToggleText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '900',
  },
  timeToggleTextActive: {
    color: '#0284C7',
  },
  saveButton: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: '#0284C7',
    columnGap: 7,
    marginTop: 2,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
});
