import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F6F8FB',
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 34,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  headerButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
  },
  headerTitleBlock: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  headerEyebrow: {
    color: '#0284C7',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  headerTitle: {
    color: '#0F172A',
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
    marginTop: 2,
  },
  heroPreview: {
    height: 236,
    overflow: 'hidden',
    borderRadius: 28,
    backgroundColor: '#0F172A',
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.36)',
  },
  heroContent: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 18,
  },
  categoryPreview: {
    alignSelf: 'flex-start',
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.94)',
    paddingHorizontal: 11,
    columnGap: 6,
    marginBottom: 12,
  },
  categoryPreviewText: {
    color: '#0369A1',
    fontSize: 13,
    fontWeight: '900',
  },
  previewTitle: {
    color: '#FFFFFF',
    fontSize: 30,
    lineHeight: 36,
    fontWeight: '900',
  },
  previewLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 6,
    marginTop: 8,
  },
  previewLocation: {
    flex: 1,
    color: '#E0F2FE',
    fontSize: 14,
    fontWeight: '800',
  },
  noticeCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderRadius: 20,
    backgroundColor: '#DFF7EA',
    paddingHorizontal: 14,
    paddingVertical: 13,
    columnGap: 10,
    marginTop: 14,
  },
  noticeText: {
    flex: 1,
    color: '#047857',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '700',
  },
  formCard: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 26,
    backgroundColor: '#FFFFFF',
    padding: 16,
    marginTop: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 22,
    marginBottom: 12,
  },
  sectionEyebrow: {
    color: '#0284C7',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  sectionTitle: {
    color: '#0F172A',
    fontSize: 21,
    lineHeight: 27,
    fontWeight: '900',
    marginBottom: 14,
  },
  sectionAction: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 19,
    backgroundColor: '#E0F2FE',
    paddingHorizontal: 12,
    columnGap: 5,
  },
  sectionActionText: {
    color: '#0284C7',
    fontSize: 13,
    fontWeight: '900',
  },
  label: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  inputShell: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 18,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 14,
    columnGap: 10,
    marginBottom: 16,
  },
  input: {
    flex: 1,
    minHeight: 52,
    color: '#0F172A',
    fontSize: 15,
    fontWeight: '700',
    paddingVertical: 0,
  },
  textAreaShell: {
    alignItems: 'flex-start',
    paddingTop: 15,
  },
  textArea: {
    minHeight: 92,
    lineHeight: 21,
    textAlignVertical: 'top',
    paddingTop: 0,
    paddingBottom: 10,
  },
  chipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  chip: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 21,
    backgroundColor: '#E0F2FE',
    paddingHorizontal: 12,
    columnGap: 7,
  },
  chipActive: {
    backgroundColor: '#0284C7',
  },
  chipText: {
    color: '#0284C7',
    fontSize: 13,
    fontWeight: '900',
  },
  chipTextActive: {
    color: '#FFFFFF',
  },
  featureChip: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 21,
    backgroundColor: '#DFF7EA',
    paddingHorizontal: 12,
    columnGap: 7,
  },
  featureChipActive: {
    backgroundColor: '#047857',
  },
  featureChipText: {
    color: '#047857',
    fontSize: 13,
    fontWeight: '900',
  },
  featureChipTextActive: {
    color: '#FFFFFF',
  },
  uploadBox: {
    minHeight: 156,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#BAE6FD',
    borderRadius: 22,
    backgroundColor: '#F0F9FF',
    padding: 18,
  },
  uploadPreview: {
    width: '100%',
    height: 168,
    borderRadius: 18,
  },
  uploadIcon: {
    width: 54,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: '#E0F2FE',
    marginBottom: 12,
  },
  uploadTitle: {
    color: '#0F172A',
    fontSize: 16,
    fontWeight: '900',
  },
  uploadSubtitle: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 5,
  },
  promotionList: {
    rowGap: 12,
  },
  promotionCard: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    padding: 14,
  },
  promotionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  promotionStatus: {
    minHeight: 32,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    paddingHorizontal: 10,
    columnGap: 6,
  },
  promotionStatusActive: {
    backgroundColor: '#DFF7EA',
  },
  promotionStatusInactive: {
    backgroundColor: '#F1F5F9',
  },
  promotionStatusText: {
    color: '#047857',
    fontSize: 12,
    fontWeight: '900',
  },
  promotionStatusTextInactive: {
    color: '#64748B',
  },
  localToggleButton: {
    width: 40,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  promotionTitle: {
    color: '#0F172A',
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '900',
    marginTop: 12,
  },
  promotionSchedule: {
    color: '#64748B',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
    marginTop: 6,
  },
  promotionActions: {
    flexDirection: 'row',
    columnGap: 10,
    marginTop: 14,
  },
  secondaryAction: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 19,
    backgroundColor: '#E0F2FE',
    paddingHorizontal: 13,
    columnGap: 6,
  },
  secondaryActionText: {
    color: '#0369A1',
    fontSize: 13,
    fontWeight: '900',
  },
  dangerAction: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 19,
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 13,
    columnGap: 6,
  },
  dangerActionText: {
    color: '#DC2626',
    fontSize: 13,
    fontWeight: '900',
  },
  emptyPromoCard: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 22,
    paddingVertical: 26,
  },
  emptyPromoTitle: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '900',
    marginTop: 10,
  },
  emptyPromoText: {
    color: '#64748B',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 6,
  },
  publishButton: {
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: '#0284C7',
    columnGap: 8,
    marginTop: 20,
    shadowColor: '#0284C7',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
    elevation: 7,
  },
  publishButtonDisabled: {
    opacity: 0.72,
  },
  publishButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },

  // Legacy keys kept for older imported components.
  promoCard: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    padding: 12,
    marginBottom: 12,
  },
  promoBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    marginBottom: 4,
  },
  toggleContainer: {
    width: 40,
    height: 22,
    borderRadius: 11,
    padding: 3,
  },
  toggleCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
  },
  button: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: '#0284C7',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  linkText: {
    color: '#0284C7',
    fontWeight: '900',
  },
});
