import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F6F8FB',
  },
  centerScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F6F8FB',
  },
  loadingText: {
    color: '#475569',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 14,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 112,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  headerEyebrow: {
    color: '#0284C7',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  headerTitle: {
    color: '#0F172A',
    fontSize: 30,
    lineHeight: 37,
    fontWeight: '900',
    marginTop: 2,
  },
  headerButton: {
    width: 46,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 23,
    backgroundColor: '#0284C7',
    shadowColor: '#0284C7',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 7,
  },
  heroCard: {
    borderRadius: 28,
    backgroundColor: '#0F766E',
    padding: 18,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 8,
  },
  heroIcon: {
    width: 54,
    height: 54,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.18)',
    marginBottom: 18,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 26,
    lineHeight: 32,
    fontWeight: '900',
  },
  heroSubtitle: {
    color: '#CCFBF1',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '600',
    marginTop: 8,
  },
  heroButton: {
    alignSelf: 'flex-start',
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 15,
    columnGap: 7,
    marginTop: 18,
  },
  heroButtonText: {
    color: '#0F766E',
    fontSize: 14,
    fontWeight: '900',
  },
  statsGrid: {
    flexDirection: 'row',
    columnGap: 10,
    marginTop: 14,
  },
  statCard: {
    flex: 1,
    minHeight: 122,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    padding: 13,
  },
  statIcon: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    marginBottom: 12,
  },
  placeIcon: {
    backgroundColor: '#E0F2FE',
  },
  promoIcon: {
    backgroundColor: '#DFF7EA',
  },
  activeIcon: {
    backgroundColor: '#FEF3C7',
  },
  statValue: {
    color: '#0F172A',
    fontSize: 24,
    fontWeight: '900',
  },
  statLabel: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 3,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 24,
    marginBottom: 12,
  },
  sectionEyebrow: {
    color: '#0284C7',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  sectionTitle: {
    color: '#0F172A',
    fontSize: 21,
    lineHeight: 27,
    fontWeight: '900',
    marginTop: 2,
  },
  sectionAction: {
    minHeight: 38,
    justifyContent: 'center',
    borderRadius: 19,
    backgroundColor: '#E0F2FE',
    paddingHorizontal: 13,
  },
  sectionActionText: {
    color: '#0284C7',
    fontSize: 13,
    fontWeight: '900',
  },
  placeList: {
    rowGap: 12,
  },
  placeCard: {
    minHeight: 104,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    padding: 12,
  },
  placeImage: {
    width: 78,
    height: 78,
    borderRadius: 20,
    backgroundColor: '#CBD5E1',
  },
  placeContent: {
    flex: 1,
    marginLeft: 12,
  },
  placeName: {
    color: '#0F172A',
    fontSize: 17,
    fontWeight: '900',
  },
  placeMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 5,
    marginTop: 6,
  },
  placeLocation: {
    flex: 1,
    color: '#64748B',
    fontSize: 13,
    fontWeight: '700',
  },
  placePromotionText: {
    color: '#0284C7',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 8,
  },
  emptyCard: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 26,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 24,
    paddingVertical: 30,
  },
  emptyIcon: {
    width: 58,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: '#E0F2FE',
    marginBottom: 14,
  },
  emptyTitle: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  emptyText: {
    color: '#64748B',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 6,
  },
  emptyButton: {
    minHeight: 44,
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: '#0284C7',
    paddingHorizontal: 18,
    marginTop: 16,
  },
  emptyButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
});

export default styles;
