import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F6F8FB',
  },
  centerScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F6F8FB',
  },
  loadingText: {
    color: '#475569',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 14,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 112,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  headerEyebrow: {
    color: '#0284C7',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  headerTitle: {
    color: '#0F172A',
    fontSize: 30,
    lineHeight: 37,
    fontWeight: '900',
    marginTop: 2,
  },
  headerButton: {
    width: 46,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 23,
    backgroundColor: '#0284C7',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 18,
    marginBottom: 12,
  },
  sectionEyebrow: {
    color: '#0284C7',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  sectionTitle: {
    color: '#0F172A',
    fontSize: 21,
    lineHeight: 27,
    fontWeight: '900',
    marginTop: 2,
  },
  countPill: {
    minWidth: 38,
    minHeight: 38,
    overflow: 'hidden',
    borderRadius: 19,
    backgroundColor: '#E0F2FE',
    color: '#0284C7',
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'center',
    textAlignVertical: 'center',
    paddingTop: 9,
  },
  sectionAction: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 19,
    backgroundColor: '#E0F2FE',
    paddingHorizontal: 12,
    columnGap: 5,
  },
  sectionActionText: {
    color: '#0284C7',
    fontSize: 13,
    fontWeight: '900',
  },
  placeList: {
    rowGap: 12,
  },
  placeCard: {
    minHeight: 104,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    padding: 12,
  },
  placeCardSelected: {
    borderColor: '#7DD3FC',
    backgroundColor: '#F0F9FF',
  },
  placeImage: {
    width: 78,
    height: 78,
    borderRadius: 20,
    backgroundColor: '#CBD5E1',
  },
  placeContent: {
    flex: 1,
    marginLeft: 12,
  },
  placeName: {
    color: '#0F172A',
    fontSize: 17,
    fontWeight: '900',
  },
  placeLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 5,
    marginTop: 6,
  },
  placeLocation: {
    flex: 1,
    color: '#64748B',
    fontSize: 13,
    fontWeight: '700',
  },
  selectedMark: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: '#F1F5F9',
  },
  selectedMarkActive: {
    backgroundColor: '#0284C7',
  },
  selectedPanel: {
    height: 190,
    overflow: 'hidden',
    borderRadius: 28,
    backgroundColor: '#0F172A',
    marginTop: 16,
  },
  selectedImage: {
    width: '100%',
    height: '100%',
  },
  selectedOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.34)',
  },
  selectedContent: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 18,
  },
  selectedTitle: {
    color: '#FFFFFF',
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
  },
  selectedLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 6,
    marginTop: 8,
  },
  selectedLocation: {
    flex: 1,
    color: '#E0F2FE',
    fontSize: 14,
    fontWeight: '700',
  },
  loadingPromotions: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    columnGap: 10,
  },
  loadingPromotionText: {
    color: '#475569',
    fontSize: 14,
    fontWeight: '700',
  },
  promotionList: {
    rowGap: 12,
  },
  promotionCard: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    padding: 14,
  },
  promotionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  promotionStatus: {
    minHeight: 32,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    paddingHorizontal: 10,
    columnGap: 6,
  },
  promotionStatusActive: {
    backgroundColor: '#DFF7EA',
  },
  promotionStatusInactive: {
    backgroundColor: '#F1F5F9',
  },
  promotionStatusText: {
    color: '#047857',
    fontSize: 12,
    fontWeight: '900',
  },
  promotionStatusTextInactive: {
    color: '#64748B',
  },
  toggleButton: {
    width: 40,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  promotionTitle: {
    color: '#0F172A',
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '900',
    marginTop: 12,
  },
  promotionSchedule: {
    color: '#64748B',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
    marginTop: 6,
  },
  promotionActions: {
    flexDirection: 'row',
    columnGap: 10,
    marginTop: 14,
  },
  secondaryAction: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 19,
    backgroundColor: '#E0F2FE',
    paddingHorizontal: 13,
    columnGap: 6,
  },
  secondaryActionText: {
    color: '#0369A1',
    fontSize: 13,
    fontWeight: '900',
  },
  dangerAction: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 19,
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 13,
    columnGap: 6,
  },
  dangerActionText: {
    color: '#DC2626',
    fontSize: 13,
    fontWeight: '900',
  },
  emptyCard: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 26,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 24,
    paddingVertical: 30,
    marginTop: 20,
  },
  emptyIcon: {
    width: 58,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: '#E0F2FE',
    marginBottom: 14,
  },
  emptyTitle: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  emptyText: {
    color: '#64748B',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 6,
  },
  emptyButton: {
    minHeight: 44,
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: '#0284C7',
    paddingHorizontal: 18,
    marginTop: 16,
  },
  emptyButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  emptyPromoCard: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 22,
    paddingVertical: 26,
  },
  emptyPromoIcon: {
    width: 58,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: '#E0F2FE',
    marginBottom: 12,
  },
  emptyPromoTitle: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '900',
  },
  emptyPromoText: {
    color: '#64748B',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 6,
  },
  emptyPromoButton: {
    minHeight: 42,
    justifyContent: 'center',
    borderRadius: 21,
    backgroundColor: '#0284C7',
    paddingHorizontal: 18,
    marginTop: 16,
  },
  emptyPromoButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
});

export default styles;
