import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F6F8FB',
  },
  centerScreen: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F6F8FB',
    paddingHorizontal: 28,
  },
  listContent: {
    paddingBottom: 178,
  },
  hero: {
    minHeight: 360,
    backgroundColor: '#0F172A',
  },
  heroImage: {
    resizeMode: 'cover',
  },
  heroOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.52)',
  },
  heroSafeArea: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 28,
    justifyContent: 'space-between',
  },
  heroTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  roundButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: 'rgba(15, 23, 42, 0.52)',
  },
  heroContent: {
    maxWidth: 330,
  },
  heroEyebrow: {
    color: '#BAE6FD',
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  placeName: {
    color: '#FFFFFF',
    fontSize: 31,
    lineHeight: 38,
    fontWeight: '900',
    marginTop: 6,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 14,
    marginTop: 18,
  },
  scoreValue: {
    color: '#38BDF8',
    fontSize: 55,
    lineHeight: 62,
    fontWeight: '900',
  },
  scoreSubtitle: {
    color: '#E0F2FE',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 5,
  },
  summaryCard: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 26,
    backgroundColor: '#FFFFFF',
    padding: 16,
    marginHorizontal: 18,
    marginTop: -34,
    marginBottom: 16,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 8,
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  summaryTitle: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '900',
  },
  summarySubtitle: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 3,
  },
  ratingBars: {
    rowGap: 8,
  },
  ratingBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 10,
  },
  ratingBarStar: {
    width: 16,
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '900',
  },
  ratingBarTrack: {
    flex: 1,
    height: 9,
    overflow: 'hidden',
    borderRadius: 5,
    backgroundColor: '#E2E8F0',
  },
  ratingBarFill: {
    height: '100%',
    borderRadius: 5,
    backgroundColor: '#0284C7',
  },
  ratingBarPercent: {
    width: 34,
    color: '#64748B',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
  },
  reviewGap: {
    height: 14,
  },
  reviewCard: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    padding: 14,
    marginHorizontal: 18,
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reviewAvatar: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: '#E2E8F0',
  },
  reviewAvatarFallback: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: '#E0F2FE',
  },
  reviewAvatarText: {
    color: '#0369A1',
    fontSize: 17,
    fontWeight: '900',
  },
  reviewTitleBlock: {
    flex: 1,
    marginLeft: 12,
  },
  reviewName: {
    color: '#0F172A',
    fontSize: 16,
    fontWeight: '900',
  },
  reviewStarsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    marginLeft: -5,
  },
  reviewDate: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 8,
  },
  reviewContent: {
    color: '#475569',
    fontSize: 15,
    lineHeight: 23,
    fontWeight: '600',
    marginTop: 13,
  },
  reviewImages: {
    columnGap: 9,
    paddingTop: 12,
  },
  reviewImage: {
    width: 132,
    height: 94,
    borderRadius: 17,
    backgroundColor: '#E2E8F0',
  },
  reviewActions: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 16,
    marginTop: 13,
  },
  reviewActionButton: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 17,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 10,
    columnGap: 6,
  },
  likeText: {
    color: '#0284C7',
    fontSize: 13,
    fontWeight: '900',
  },
  reportText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '800',
  },
  emptyReviews: {
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 24,
    paddingVertical: 30,
    marginHorizontal: 18,
  },
  emptyIcon: {
    width: 58,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: '#E0F2FE',
    marginBottom: 14,
  },
  emptyTitle: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 10,
  },
  emptyText: {
    color: '#64748B',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 6,
  },
  emptyButton: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: '#0284C7',
    paddingHorizontal: 20,
    marginTop: 16,
  },
  emptyButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  pendingImagesBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingTop: 10,
    gap: 8,
  },
  pendingImageWrap: {
    position: 'relative',
  },
  pendingImage: {
    width: 54,
    height: 54,
    borderRadius: 14,
    backgroundColor: '#E2E8F0',
  },
  removeImageButton: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: '#DC2626',
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 12,
    columnGap: 10,
  },
  photoButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: '#E0F2FE',
    marginBottom: 1,
  },
  inputContent: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 22,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 9,
  },
  ratingPicker: {
    flexDirection: 'row',
    columnGap: 3,
    marginBottom: 4,
  },
  textInput: {
    minHeight: 24,
    maxHeight: 90,
    color: '#0F172A',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    padding: 0,
  },
  sendButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: '#0284C7',
    marginBottom: 1,
  },
  sendButtonDisabled: {
    backgroundColor: '#CBD5E1',
  },
});

export default styles;
